name: Build StocksShorts APK
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: npm install
    - run: npm run build
    - run: npx cap sync android
    - run: cd android && chmod +x gradlew && ./gradlew assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: stocksshorts-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
